name = "InplaceOps"
uuid = "3c135089-5b96-4691-be75-a7e5cfd4e4d6"
authors = ["Simon Byrne <simonbyrne@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
